# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Mailosaur
  module Models
    #
    # Model object.
    #
    #
    class Link
      # @return [String]
      attr_accessor :href

      # @return [String]
      attr_accessor :text


      #
      # Mapper for Link class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'Link',
          type: {
            name: 'Composite',
            class_name: 'Link',
            model_properties: {
              href: {
                client_side_validation: true,
                required: false,
                serialized_name: 'href',
                type: {
                  name: 'String'
                }
              },
              text: {
                client_side_validation: true,
                required: false,
                serialized_name: 'text',
                type: {
                  name: 'String'
                }
              }
            }
          }
        }
      end
    end
  end
end
