# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Mailosaur
  module Models
    #
    # Model object.
    #
    #
    class MessageAddress
      # @return [String]
      attr_accessor :name

      # @return [String]
      attr_accessor :email

      # @return [String]
      attr_accessor :phone


      #
      # Mapper for MessageAddress class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'MessageAddress',
          type: {
            name: 'Composite',
            class_name: 'MessageAddress',
            model_properties: {
              name: {
                client_side_validation: true,
                required: false,
                serialized_name: 'name',
                type: {
                  name: 'String'
                }
              },
              email: {
                client_side_validation: true,
                required: false,
                serialized_name: 'email',
                type: {
                  name: 'String'
                }
              },
              phone: {
                client_side_validation: true,
                required: false,
                serialized_name: 'phone',
                type: {
                  name: 'String'
                }
              }
            }
          }
        }
      end
    end
  end
end
