# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Mailosaur
  module Models
    #
    # Model object.
    #
    #
    class MessageSummary
      # @return
      attr_accessor :id

      # @return [String]
      attr_accessor :server

      # @return [Array<MessageAddress>]
      attr_accessor :rcpt

      # @return [Array<MessageAddress>]
      attr_accessor :from

      # @return [Array<MessageAddress>]
      attr_accessor :to

      # @return [Array<MessageAddress>]
      attr_accessor :cc

      # @return [Array<MessageAddress>]
      attr_accessor :bcc

      # @return [DateTime]
      attr_accessor :received

      # @return [String]
      attr_accessor :subject

      # @return [String]
      attr_accessor :summary

      # @return [Integer]
      attr_accessor :attachments


      #
      # Mapper for MessageSummary class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'MessageSummary',
          type: {
            name: 'Composite',
            class_name: 'MessageSummary',
            model_properties: {
              id: {
                client_side_validation: true,
                required: true,
                serialized_name: 'id',
                type: {
                  name: 'String'
                }
              },
              server: {
                client_side_validation: true,
                required: false,
                serialized_name: 'server',
                type: {
                  name: 'String'
                }
              },
              rcpt: {
                client_side_validation: true,
                required: false,
                serialized_name: 'rcpt',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageAddressElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageAddress'
                      }
                  }
                }
              },
              from: {
                client_side_validation: true,
                required: false,
                serialized_name: 'from',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageAddressElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageAddress'
                      }
                  }
                }
              },
              to: {
                client_side_validation: true,
                required: false,
                serialized_name: 'to',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageAddressElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageAddress'
                      }
                  }
                }
              },
              cc: {
                client_side_validation: true,
                required: false,
                serialized_name: 'cc',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageAddressElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageAddress'
                      }
                  }
                }
              },
              bcc: {
                client_side_validation: true,
                required: false,
                serialized_name: 'bcc',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageAddressElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageAddress'
                      }
                  }
                }
              },
              received: {
                client_side_validation: true,
                required: false,
                serialized_name: 'received',
                type: {
                  name: 'DateTime'
                }
              },
              subject: {
                client_side_validation: true,
                required: false,
                serialized_name: 'subject',
                type: {
                  name: 'String'
                }
              },
              summary: {
                client_side_validation: true,
                required: false,
                serialized_name: 'summary',
                type: {
                  name: 'String'
                }
              },
              attachments: {
                client_side_validation: true,
                required: false,
                serialized_name: 'attachments',
                type: {
                  name: 'Number'
                }
              }
            }
          }
        }
      end
    end
  end
end
