# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Mailosaur
  module Models
    #
    # Model object.
    #
    #
    class Metadata
      # @return [Array<MessageHeader>]
      attr_accessor :headers


      #
      # Mapper for Metadata class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'Metadata',
          type: {
            name: 'Composite',
            class_name: 'Metadata',
            model_properties: {
              headers: {
                client_side_validation: true,
                required: false,
                serialized_name: 'headers',
                type: {
                  name: 'Sequence',
                  element: {
                      client_side_validation: true,
                      required: false,
                      serialized_name: 'MessageHeaderElementType',
                      type: {
                        name: 'Composite',
                        class_name: 'MessageHeader'
                      }
                  }
                }
              }
            }
          }
        }
      end
    end
  end
end
