# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Mailosaur
  module Models
    #
    # Model object.
    #
    #
    class SpamAssassinRule
      # @return [Float]
      attr_accessor :score

      # @return [String]
      attr_accessor :rule

      # @return [String]
      attr_accessor :description


      #
      # Mapper for SpamAssassinRule class as Ruby Hash.
      # This will be used for serialization/deserialization.
      #
      def self.mapper()
        {
          client_side_validation: true,
          required: false,
          serialized_name: 'SpamAssassinRule',
          type: {
            name: 'Composite',
            class_name: 'SpamAssassinRule',
            model_properties: {
              score: {
                client_side_validation: true,
                required: false,
                serialized_name: 'score',
                type: {
                  name: 'Double'
                }
              },
              rule: {
                client_side_validation: true,
                required: false,
                serialized_name: 'rule',
                type: {
                  name: 'String'
                }
              },
              description: {
                client_side_validation: true,
                required: false,
                serialized_name: 'description',
                type: {
                  name: 'String'
                }
              }
            }
          }
        }
      end
    end
  end
end
